//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerShopEntities : DbContext
    {
        public ComputerShopEntities()
            : base("name=ComputerShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Cooler> Cooler { get; set; }
        public virtual DbSet<Corpus> Corpus { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<MemoryType> MemoryType { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<PowerModule> PowerModule { get; set; }
        public virtual DbSet<Processor> Processor { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeVideoMemory> TypeVideoMemory { get; set; }
        public virtual DbSet<VideoCard> VideoCard { get; set; }
    }
}
