//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motherboard()
        {
            this.PC = new HashSet<PC>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public decimal SerialNumber { get; set; }
        public string Chipset { get; set; }
        public int MemorySlots { get; set; }
        public decimal Price { get; set; }
        public int MemoryTypeID { get; set; }
        public int ManufacturerID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MemoryType MemoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
    }
}
