//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public int MotherboardID { get; set; }
        public int ProcessorID { get; set; }
        public int RAM_ID { get; set; }
        public int VideocardID { get; set; }
        public int PowerModuleID { get; set; }
        public int CoolerID { get; set; }
        public int СorpusID { get; set; }
    
        public virtual Cooler Cooler { get; set; }
        public virtual Corpus Corpus { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual PowerModule PowerModule { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual VideoCard VideoCard { get; set; }
    }
}
